name: CI / CD

on:
  push:
    branches: [ master ]

env:
  SERVICE_NAME: connect

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build / Deploy

    steps:
    - uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        export_default_credentials: true
        
    - name: Generate container image
      run: |
        gcloud builds submit \
          --tag "us.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/SERVICE_NAME:$GITHUB_SHA" .
           
    - name: Deploy do Cloud Run
      run: |
        gcloud run deploy "$SERVICE_NAME" \
          --region "us-central1" \
          --image "us.gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
       
